#datasource
spring.datasource.url=${db_url}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=ture
spring.jpa.properties.hibernate.order_updates=ture
spring.jpa.properties.hibernate.order_deletes=ture

#liquibase
spring.liquibase.enabled=true
spring.liquibase.contexts=dev
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#logging
logging.level.com.github.svenfran.budgetapp.budgetappbackend=TRACE

#spring-security
logging.level.org.springframework.security=DEBUG

#brevo-email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER}
brevo.sender.name=${BREVO_APP_NAME}

#websocket
websocket.url=/ws

#actuator
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

#language
spring.messages.basename=messages
spring.messages.encoding=UTF-8

#scheduled-tasks
task.recurringCart.schedule=*/15 * * * * *
task.clearToken.schedule=0 0 * * * *

#port
server.port=9090
