#datasource
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=ture
spring.jpa.properties.hibernate.order_updates=ture
spring.jpa.properties.hibernate.order_deletes=ture

#liquibase
spring.liquibase.enabled=true
spring.liquibase.contexts=prod
spring.liquibase.default-schema=public
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master-prod.xml

#logging
logging.level.com.github.svenfran.budgetapp.budgetappbackend=TRACE

#spring-security
logging.level.org.springframework.security=DEBUG

#brevo-email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER}
brevo.sender.name=${BREVO_APP_NAME}

#websocket
websocket.url=/wss

#actuator
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

#language
spring.messages.basename=messages
spring.messages.encoding=UTF-8

#scheduled-tasks
task.recurringCart.schedule=0 0 1 * * *
task.clearToken.schedule=0 0 0 * * ?
